### ISSUE TITLE
Badge not centered in Safari

### ISSUE THREAD

**Issue by JaySunSyn** [MaritzSTL/mtz-wizard#8]
Hi - thanks a lot for the element!

The badge number seems to be not centered in a Safari browser.

![image](https://user-images.githubusercontent.com/5872432/29223070-7e3f33fa-7ec5-11e7-9b9c-0e0d96d41942.png)

**Comment by stramel** [comment]
Thanks for reporting this issue! I will take a look at it today.

**Comment by stramel** [comment]
Fixed in v0.1.5 :tada:
